FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY wrdn/backend/requirements.txt /app/requirements.txt

RUN pip install \
    --no-cache-dir \
    -r /app/requirements.txt

COPY wrdn /app/wrdn

RUN mkdir -p /app/wrdn/backend/data

EXPOSE 8000

CMD ["uvicorn", "wrdn.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]